### ISSUE TITLE
train.py normalization should be valid

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/openmapflow#14]
**Context**: The `train.py` example script contains all the code to train any PyTorch model on available data.

**Issue**: The current data normalization done inside the model is not valid for the ERA5 bands of the data: https://github.com/nasaharvest/openmapflow/blob/a0533afe8a607a9ab95b6d628f310dea45e61d8f/openmapflow/templates/train.py#L79

**Potential solution**: Use per band scaling values.

**Comment by ivanzvonkov** [comment]
After regenerating all example projects with this code I found that the models could not be saved with `torch.jit.script`, running the train.py script produced:
```
Traceback (most recent call last):
  File "/Users/izvonkov/nasaharvest/openmapflow/buildings-example/train.py", line 216, in <module>
    sm = torch.jit.script(model)
  File "/Users/izvonkov/nasaharvest/openmapflow/venv/lib/python3.9/site-packages/torch/jit/_script.py", line 1265, in script
    return torch.jit._recursive.create_script_module(
  File "/Users/izvonkov/nasaharvest/openmapflow/venv/lib/python3.9/site-packages/torch/jit/_recursive.py", line 454, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/Users/izvonkov/nasaharvest/openmapflow/venv/lib/python3.9/site-packages/torch/jit/_recursive.py", line 520, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/Users/izvonkov/nasaharvest/openmapflow/venv/lib/python3.9/site-packages/torch/jit/_recursive.py", line 371, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
python value of type 'list' cannot be used as a value. Perhaps it is a closed over global variable? If so, please consider passing it in as an argument or use a local varible instead.:
  File "/Users/izvonkov/nasaharvest/openmapflow/buildings-example/train.py", line 90
    def forward(self, x):
        with torch.no_grad():
            x = x / torch.tensor(BANDS_MAX)
                                 ~~~~~~~~~ <--- HERE
            x = x.transpose(2, 1)
        x = self.model(x).squeeze(dim=1)
```

I think we missed this because the #28 updated the template train.py but did not regenerate each project's train.py.

I have reverted the change in #68 and added integration tests to make it easier to catch these errors. 
Projects still have to be regenerated manually if there is a change to the template files.

**Comment by ivanzvonkov** [comment]
Fixed by https://github.com/nasaharvest/openmapflow/pull/69
